name: Test Suite

on: [push]

jobs:
  nightly:
    name: Tests and produces nightly assets.
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Run test script.
      run: |
        git clone https://github.com/Embroidermodder/embroidermodder
        cd embroidermodder
        pip install libembroidery
        python3 embroidermodder.py
      shell: bash
